---

- name: Delete default user
  action: user
          name=pi
          state=absent

- name: Delete default group
  action: group
          name=pi
          state=absent

- name: Delete default user home
  file: path=/home/pi
        state=absent
